rebuild for kernel 5.7.7, disable generate debug package
thanks to new toolchains in Cooker, some packages failed to build due to:
error: Empty %files file /builddir/build/BUILD/nvidia-440-440.82/debugsourcefiles.list
workaround is disable debug packages